### ISSUE TITLE
"Expected length for sequenceNumber event is 2"

### ISSUE THREAD

**Issue by pasqLisena** [carter-thaxton/midi-file#4]
I got this exception:
> Expected length for sequenceNumber event is 2, got 48

fired here: 
https://github.com/carter-thaxton/midi-file/blob/master/lib/midi-parser.js#L78

What is the role of the sequenceNumber? Why it can't have a different length?

**Comment by carter-thaxton** [comment]
https://stackoverflow.com/questions/13065209/sequence-number-in-a-midi-file-how-does-it-work
http://midi.teragonaudio.com/tech/midifile/seq.htm

I don't entirely understand the sequenceNumber either.  It seems like it's just an optional 16-bit number that can be used as an identifier.  I do think it needs to be length 2 (16-bits).  If you're getting a value of 48, there's probably something else wrong in your MIDI file.  Doesn't seem to make much sense as a 48-byte value (8*48 = 384-bit number).  I've never run across this myself.
